### ISSUE TITLE
All commands in context menu are disabled

### ISSUE THREAD

**Issue by Ragsboss** [gdeOo/sublime-sourcetree#2]
Mac OS X El Capitan (10.11.2)
Sublime Text 3 Beta (Build 3083)
Source Tree v2.1
SourceTreeCommands Plugin v1.0

I ensured /usr/local/bin/stree is properly setup and I also set following settings in my global user settings file. 
    "detect_sourcetree": false,
    "find_selected_text": true,
But I notice that all 3 context menu commands are disabled, no matter what I tried. I don't see anything relevant in Sublime Text Console..

Any help is appreciated

**Comment by gdeOo** [comment]
There is a bug that makes the commands become disabled forever when launching sublime text.

Just to make sure, can you try this and check if the commands get enabled at the end?
- Launch sublime text (commands should be disabled)
- Go into the package's folder ("Preferences > Browse Packages...", SourceTreeCommands folder)
- Open sublime-sourcetree.py, add a newline at the end and save (this will make sublime reload the package)

**Comment by gdeOo** [comment]
Should be fixed in v1.1.0
